services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3002:3000"
    depends_on:
      - backend
    networks:
      - ecommerce-network

  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    networks:
      - ecommerce-network
    environment:
      MONGO_URL: mongodb://mongo:27017/ecommerce

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - ecommerce-network
    volumes:
      - mongo-data:/data/db

networks:
  ecommerce-network:
    driver: bridge

volumes:
  mongo-data:
